### PR TITLE
Moved React to a Peer Dependency (and Dev Dependency)

### PR DESCRIPTION
**Pull request by riceboyler**
Reusable React components shouldn't have React as a pure dependency due to versioning issues. In this PR, I moved React to a peerDependency and devDependency in order to resolve an issue with versioning we're having at our company.

For more information about React and dependencies, see this link: https://stackoverflow.com/questions/30451556/what-is-the-correct-way-of-adding-a-dependency-to-react-in-your-package-json-for

### CODE REVIEW

**Comment by aiham** [comment]
@riceboyler Thanks! Could you please remove the .idea/workspace.xml file?

**Comment by riceboyler** [comment]
Done, sorry about that. I thought I had removed it.

**Comment by riceboyler** [comment]
Thanks for the QUICK work on this!

**Comment by riceboyler** [comment]
@aiham Any idea what's causing the build to fail? Looks like a specific library that Chrome needs is failing.

**Comment by aiham** [comment]
Yeah chrome isn't installing correctly. I haven't tried just iyet but
upgrading to ubuntu trusty is probably going to do the trick. I'll fix it
in a separate PR. Thanks

**Comment by ckuiawa** [comment]
Are you going to be able to release a version with this change?  The alternative is that I need to fork this repo, change the package name, apply this fix, publish to my local npm server, and change my projects that depend on this.

**Comment by aiham** [comment]
@riceboyler Yeah upgrading to Ubuntu Trusty did the trick: https://travis-ci.org/aiham/opentok-react/builds/265806471

**Comment by aiham** [comment]
@riceboyler @ckuiawa Published to npm as v0.7.0

@ckuiawa For future reference, you can reference a package that hasn't been published to npm but is on github:

```
  "dependencies": {
    "opentok-react": "aiham/opentok-react#dev"
  }
```

The phrase after the # is the desired branch name.

**Pull request merged**
